add a set of table functions to query pg scheme. Filenames are now added to sqlpgq config
cwida/duckdb-pgq pull request #56
Opened 2023-04-06 12:25 UTC by vlowingkloude

2023-04-11 11:58 UTC, Dtenwolde requested changes
Thanks for the PR, just a couple of comments :)

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +                throw InternalException("The SQL/PGQ extension has not been loaded");
Please change the InternalException to MissingExtensionException :)

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/include/sqlpgq_functions.hpp
> +                vector<CreateTableFunctionInfo> functions;
Please run `make format-fix` (If you didn't do that already), not sure if that will fix this formatting 'issue' but better be safe than sorry. (I don't care too much about the CI at the moment as we will switch to a different repo and CI in the near future but still

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +        for(auto ele : table_entry -> column_names) {
Think this can be `const auto &ele : table_entry->column_names` (also didn't know there can be spaces between the `->`)

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +	return nullptr;
unable to reach this

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +        auto csrID = ((CSRScanWData *)(data_p.bind_data))->csrID;
please make naming consistent (See https://github.com/duckdb/duckdb/blob/master/CONTRIBUTING.md), so should be csr_id

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +                throw InternalException("The SQL/PGQ extension has not been loaded");
Please change to MissingExtensionException

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +                throw InternalException("The SQL/PGQ extension has not been loaded");
MissingExtensionException

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +                throw InternalException("The SQL/PGQ extension has not been loaded");
MissingExtensionException

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +                throw InternalException("The SQL/PGQ extension has not been loaded");
MissingExtensionException

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +                throw InternalException("The SQL/PGQ extension has not been loaded");
MissingExtensionException

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/sqlpgq_functions/sqlpgq_scan.cpp
> +                throw InternalException("The SQL/PGQ extension has not been loaded");
MissingExtensionException

2023-04-11 11:58 UTC, Dtenwolde commented on extension/sqlpgq/include/sqlpgq_scan.hpp
> +        int32_t csrID;
Please fix naming inconsistency (should be csr_id)

2023-04-17 12:49 UTC, vlowingkloude commented
I created a new branch and opened a new PR. I'll close this one.

2023-04-17 12:49 UTC, closed without merging